"""empty message

Revision ID: 39bc77d7b08d
Revises: 
Create Date: 2024-03-17 11:10:20.490876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39bc77d7b08d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sa.Enum('PORTUGUESE', 'ENGLISH', 'DEUTSCH', 'FRENCH', 'SPANISH', 'ITALIAN', 'CHINESE', 'JAPONESE', 'RUSSIAN', name='language'), nullable=False),
    sa.Column('phonetic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term',
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sa.Enum('PORTUGUESE', 'ENGLISH', 'DEUTSCH', 'FRENCH', 'SPANISH', 'ITALIAN', 'CHINESE', 'JAPONESE', 'RUSSIAN', name='language'), nullable=False),
    sa.PrimaryKeyConstraint('term', 'origin_language')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('native_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('term_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.PrimaryKeyConstraint('term', 'origin_language', 'term_level', 'type')
    )
    op.create_table('exercisespeak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termdefinition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sa.Enum('PORTUGUESE', 'ENGLISH', 'DEUTSCH', 'FRENCH', 'SPANISH', 'ITALIAN', 'CHINESE', 'JAPONESE', 'RUSSIAN', name='language'), nullable=False),
    sa.Column('term_level', sa.Enum('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'UPPER_INTERMEDIATE', 'ADVANCED', 'MASTER', name='termlevel'), nullable=True),
    sa.Column('part_of_speech', sa.Enum('ADJECTIVE', 'NOUN', 'VERB', 'ADVERB', 'CONJUNCTION', 'PREPOSITION', 'PRONOUN', 'DETERMINER', 'NUMBER', 'PREDETERMINER', 'PREFIX', 'SUFFIX', 'SLANG', name='partofspeech'), nullable=False),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termlexical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sa.Enum('PORTUGUESE', 'ENGLISH', 'DEUTSCH', 'FRENCH', 'SPANISH', 'ITALIAN', 'CHINESE', 'JAPONESE', 'RUSSIAN', name='language'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('SYNONYM', 'ANTONYM', 'FORM', name='termlexicaltype'), nullable=False),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardset_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cardset_id'], ['cardset.id'], ),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercisehistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('term_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('text_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text_request', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['origin_language'], ['exercise.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['exercise.term'], ),
    sa.ForeignKeyConstraint(['term_level'], ['exercise.term_level'], ),
    sa.ForeignKeyConstraint(['type'], ['exercise.type'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termdefinitiontranslation',
    sa.Column('language', sa.Enum('PORTUGUESE', 'ENGLISH', 'DEUTSCH', 'FRENCH', 'SPANISH', 'ITALIAN', 'CHINESE', 'JAPONESE', 'RUSSIAN', name='language'), nullable=False),
    sa.Column('term_definition_id', sa.Integer(), nullable=False),
    sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meaning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['term_definition_id'], ['termdefinition.id'], ),
    sa.PrimaryKeyConstraint('language', 'term_definition_id')
    )
    op.create_table('termexample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sa.Enum('PORTUGUESE', 'ENGLISH', 'DEUTSCH', 'FRENCH', 'SPANISH', 'ITALIAN', 'CHINESE', 'JAPONESE', 'RUSSIAN', name='language'), nullable=False),
    sa.Column('term_definition_id', sa.Integer(), nullable=True),
    sa.Column('example', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.ForeignKeyConstraint(['term_definition_id'], ['termdefinition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pronunciationlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pronunciation_id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origin_language', sa.Enum('PORTUGUESE', 'ENGLISH', 'DEUTSCH', 'FRENCH', 'SPANISH', 'ITALIAN', 'CHINESE', 'JAPONESE', 'RUSSIAN', name='language'), nullable=True),
    sa.Column('term_example_id', sa.Integer(), nullable=True),
    sa.Column('term_lexical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['pronunciation_id'], ['pronunciation.id'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.ForeignKeyConstraint(['term_example_id'], ['termexample.id'], ),
    sa.ForeignKeyConstraint(['term_lexical_id'], ['termlexical.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pronunciation_id')
    )
    op.create_table('termexampletranslation',
    sa.Column('language', sa.Enum('PORTUGUESE', 'ENGLISH', 'DEUTSCH', 'FRENCH', 'SPANISH', 'ITALIAN', 'CHINESE', 'JAPONESE', 'RUSSIAN', name='language'), nullable=False),
    sa.Column('term_example_id', sa.Integer(), nullable=False),
    sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['term_example_id'], ['termexample.id'], ),
    sa.PrimaryKeyConstraint('language', 'term_example_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('termexampletranslation')
    op.drop_table('pronunciationlink')
    op.drop_table('termexample')
    op.drop_table('termdefinitiontranslation')
    op.drop_table('exercisehistory')
    op.drop_table('card')
    op.drop_table('termlexical')
    op.drop_table('termdefinition')
    op.drop_table('exercisespeak')
    op.drop_table('exercise')
    op.drop_table('cardset')
    op.drop_table('user')
    op.drop_table('term')
    op.drop_table('pronunciation')
    # ### end Alembic commands ###
