"""create terms tables

Revision ID: 46f6d22777ee
Revises: 
Create Date: 2024-03-04 18:05:35.984306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46f6d22777ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term',
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('term', 'origin_language')
    )
    op.create_table('termdefinition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('term_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('partOfSpeech', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translation_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termlexical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termexample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('term_definition_id', sa.Integer(), nullable=True),
    sa.Column('example_translation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translation_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('example', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.ForeignKeyConstraint(['term_definition_id'], ['termdefinition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termpronunciation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translation_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('term_example_id', sa.Integer(), nullable=True),
    sa.Column('phonetic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.ForeignKeyConstraint(['term_example_id'], ['termexample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('termpronunciation')
    op.drop_table('termexample')
    op.drop_table('termlexical')
    op.drop_table('termdefinition')
    op.drop_table('term')
    # ### end Alembic commands ###
