"""create exercises tables

Revision ID: eaf5ed72e907
Revises: 33e6f277a913
Create Date: 2024-03-05 20:04:00.825069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eaf5ed72e907'
down_revision: Union[str, None] = '33e6f277a913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('term_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['origin_language'], ['term.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['term.term'], ),
    sa.PrimaryKeyConstraint('term', 'origin_language', 'term_level', 'type')
    )
    op.create_table('exercisespeak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercisehistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('term_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('text_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text_request', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['origin_language'], ['exercise.origin_language'], ),
    sa.ForeignKeyConstraint(['term'], ['exercise.term'], ),
    sa.ForeignKeyConstraint(['term_level'], ['exercise.term_level'], ),
    sa.ForeignKeyConstraint(['type'], ['exercise.type'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercisehistory')
    op.drop_table('exercisespeak')
    op.drop_table('exercise')
    # ### end Alembic commands ###
